version: '2'

services:
  db:
      image: postgres
      restart: always
      environment:
        - POSTGRES_HOST_AUTH_METHOD=trust
        - POSTGRES_USER=yura
        - POSTGRES_PASSWORD=yurapass
        - POSTGRES_DB=managment
      container_name: postgres-db
      volumes:
        - ./pgdata:/var/lib/postgresql/data

  server:
    build: ./
    image: managment-app:latest
    restart: always
    ports: 
    - "3000:3000"
    container_name: nest-managment-app
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
  
volumes:
  pgdata:
    driver: local  
  
  