services:
  web:
    build:
      dockerfile: Dockerfile
      context: .
    image: managment-app:latest
    container_name: nest-managment-app
    restart: always
    ports:
      - '5050:5050'

    environment:
      DATABASE_URL: postgres://yura:yurapass@postgres:5432/managment
      PORT: 5050
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: postgres-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=yura
      - POSTGRES_PASSWORD=yurapass
      - POSTGRES_DB=managment

build:
  postgres:
  web:
